-- 1. Criação dos Enums (Tipos personalizados)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_ferias_enum') THEN
CREATE TYPE status_ferias_enum AS ENUM ('Solicitada', 'Planejada', 'Aprovada', 'Cancelada', 'Finalizada');
END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_pagamento_enum') THEN
CREATE TYPE status_pagamento_enum AS ENUM ('Agendado', 'Pago', 'Cancelado');
END IF;
END$$;

-- 2. Criação das Tabelas
CREATE TABLE IF NOT EXISTS funcionario_servidor (
                                                    id_servidor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    funcionario_nome VARCHAR(45) NOT NULL,
    matricula INTEGER NOT NULL UNIQUE,
    email VARCHAR(45) NOT NULL,
    orgao VARCHAR(45),
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ferias (
                                      id_ferias INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      ferias_nome VARCHAR(45) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    quantidade_de_dias INTEGER,
    status status_ferias_enum NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    servidor_id_servidor INTEGER NOT NULL,
    CONSTRAINT fk_ferias_servidor FOREIGN KEY (servidor_id_servidor) REFERENCES funcionario_servidor (id_servidor)
    );

CREATE TABLE IF NOT EXISTS pagamentos (
                                          id_pagamentos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          data_pagamento DATE,
                                          valor_bruto NUMERIC(12,2),
    valor_liquido NUMERIC(12,2),
    status status_pagamento_enum NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    ferias_id_ferias INTEGER NOT NULL,
    CONSTRAINT fk_pagamentos_ferias FOREIGN KEY (ferias_id_ferias) REFERENCES ferias (id_ferias)
    );

CREATE TABLE IF NOT EXISTS status_ferias (
                                             id_status_ferias INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             status_ferias status_ferias_enum NOT NULL,
                                             data_criacao TIMESTAMP NOT NULL,
                                             ferias_id_ferias INTEGER NOT NULL,
                                             CONSTRAINT fk_status_ferias_ferias FOREIGN KEY (ferias_id_ferias) REFERENCES ferias (id_ferias)
    );

CREATE TABLE IF NOT EXISTS usuario (
                                       id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       login VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    funcionario_servidor_id_servidor INTEGER NOT NULL,
    CONSTRAINT fk_usuario_funcionario_servidor FOREIGN KEY (funcionario_servidor_id_servidor) REFERENCES funcionario_servidor (id_servidor)
    );

-- 3. INSERTS DE DADOS DE TESTE (SEED)
-- Inserir Servidor (João Silva)
INSERT INTO funcionario_servidor (funcionario_nome, matricula, email, orgao)
VALUES ('João Silva', 123456, 'joao.silva@sergipetec.org.br', 'Tecnologia');

-- Inserir Férias Passadas (Finalizada)
INSERT INTO ferias (ferias_nome, data_inicio, data_fim, quantidade_de_dias, status, data_criacao, servidor_id_servidor)
VALUES ('Férias 2024', '2024-01-02', '2024-01-31', 30, 'Finalizada', NOW(), 1);

-- Inserir Férias Futuras (Solicitada)
INSERT INTO ferias (ferias_nome, data_inicio, data_fim, quantidade_de_dias, status, data_criacao, servidor_id_servidor)
VALUES ('Férias 2025', '2025-05-01', '2025-05-15', 15, 'Solicitada', NOW(), 1);

-- Inserir Pagamento das Férias 2024
INSERT INTO pagamentos (data_pagamento, valor_bruto, valor_liquido, status, data_criacao, ferias_id_ferias)
VALUES ('2023-12-28', 5000.00, 4200.00, 'Pago', NOW(), 1);